cargoCar= {
	--################ METIER ##################
	[1] = {model ="Phantom", maxCapacity = 2},
	[2] = {model ="TrailerLogs", maxCapacity = 40},
	[3] = {model ="Tanker", maxCapacity = 70},
	[4] = {model ="tiptruck2", maxCapacity = 99},
	[5] = {model ="hauler", maxCapacity = 2},
	[6] = {model = "pounder", maxCapacity = 70},
	[7] = {model ="tiptruck", maxCapacity = 99},
	[8] = {model ="rubble", maxCapacity = 99},
	[9] = {model ="Bison3", maxCapacity = 10},
	[10] = {model ="Bison2", maxCapacity = 10},
	[11] = {model ="Bison1", maxCapacity = 10},
	[12] = {model ="sadler", maxCapacity = 50},
	[13] = {model ="Benson", maxCapacity = 99},
	[14] = {model ="tug", maxCapacity = 99},
	[15] = {model ="sadler2", maxCapacity = 50},
	[16] = {model ="flatbed", maxCapacity = 50},
	[17] = {model = "taco", maxCapacity = 99},
	[304] = {model = "boxville", maxCapacity = 100},
	[305] = {model = "mule", maxCapacity = 100},
	[306] = {model = "mule3", maxCapacity = 100},
	[300] = {model = "mule", maxCapacity = 99},
	[301] = {model = "mule3", maxCapacity = 99},
	[302] = {model = "boxville", maxCapacity = 99},
	--################ SUV ##################
	[18] = {model = "bifta", maxCapacity = 5},
    [19] = {model = "blazer", maxCapacity = 5},
    [20] = {model = "blazer4", maxCapacity = 5},
    [21] = {model = "brawler", maxCapacity = 55},
    [22] = {model = "mesa3", maxCapacity = 65} ,
    [23] = {model = "dubsta3", maxCapacity = 75},
	[24] = {model = "dune", maxCapacity = 5},
	[25] = {model = "rebel2", maxCapacity = 55},
    [26] = {model = "sandking", maxCapacity = 65},
    [27] = {model = "sandking2", maxCapacity = 65},
    [28] = {model = "contender", maxCapacity = 55},
    [29] = {model = "trophytruck", maxCapacity = 25},
    [30] = {model = "trophytruck2", maxCapacity = 25},
	[31] = {model = "baller", maxCapacity = 45},
    [32] = {model = "baller3", maxCapacity = 55},
    [33] = {model = "baller4", maxCapacity = 55},
    [34] = {model = "cavalcade", maxCapacity = 55},
    [35] = {model = "granger", maxCapacity = 65},
    [36] = {model = "huntley", maxCapacity = 45},
	[37] = {model = "landstalker", maxCapacity = 65},
	[38] = {model = "radi", maxCapacity = 25},
    [39] = {model = "rocoto", maxCapacity = 45},
    [40] = {model = "seminole", maxCapacity = 55},
	[41] = {model = "xls", maxCapacity = 50},
	--################ VANS ##################
	[42] = {model = "bison", maxCapacity = 65},
    [43] = {model = "bobcatxl", maxCapacity = 65},
    [44] = {model = "gburrito", maxCapacity = 85},
    [45] = {model = "journey", maxCapacity = 85},
    [46] = {model = "minivan", maxCapacity = 55},
    [47] = {model = "paradise", maxCapacity = 75}, 
    [48] = {model = "rumpo", maxCapacity = 75}, 
    [49] = {model = "surfer", maxCapacity = 80},
    [50] = {model = "youga", maxCapacity = 75},
	--################ COMPACTS ##################
	[50] = {model = "blista", maxCapacity = 20}, 
    [51] = {model = "brioso", maxCapacity = 20}, 
    [52] = {model = "Dilettante", maxCapacity = 20},  
    [53] = {model = "issi2", maxCapacity = 20}, 
	[54] = {model = "panto", maxCapacity = 20}, 
    [55] = {model = "prairie", maxCapacity = 20},  
    [56] = {model = "rhapsody", maxCapacity = 25}, 
	--################ SEDANS ##################
	[57] = {model = "asea", maxCapacity = 20}, 
    [58] = {model = "asterope",maxCapacity = 20}, 
    [59] = {model = "fugitive",maxCapacity = 20}, 
    [60] = {model = "glendale",maxCapacity = 20}, 
    [61] = {model = "ingot",maxCapacity = 20}, 
    [62] = {model = "intruder", maxCapacity = 20}, 
    [63] = {model = "premier", maxCapacity = 20}, 
    [64] = {model = "primo", maxCapacity = 20}, 
    [65] = {model = "primo2",maxCapacity = 20}, 
    [66] = {model = "regina",maxCapacity = 20}, 
    [67] = {model = "schafter2",maxCapacity = 30}, 
    [68] = {model = "schafter4",maxCapacity = 30}, 
    [69] = {model = "stanier",maxCapacity = 20}, 
    [70] = {model = "stratum",maxCapacity = 40}, 
    [71] = {model = "stretch",maxCapacity = 60}, 
    [72] = {model = "superd",maxCapacity = 30}, 
    [73] = {model = "surge",maxCapacity = 20}, 
    [74] = {model = "tailgater",maxCapacity = 20}, 
    [75] = {model = "warrener",maxCapacity = 20}, 
    [76] = {model = "washington", maxCapacity = 30}, 
    [77] = {model = "cognoscenti",maxCapacity = 20}, 
	--############### MUSCLES ##################
	[78] = {model = "blade", maxCapacity = 30}, 
    [79] = {model = "buccaneer",maxCapacity = 20}, 
    [80] = {model = "chino", maxCapacity = 20}, 
    [81] = {model = "coquette3",maxCapacity = 20}, 
    [82] = {model = "dominator",maxCapacity = 10}, 
    [83] = {model = "dukes",maxCapacity = 20}, 
    [84] = {model = "gauntlet",maxCapacity = 10}, 
    [85] = {model = "hotknife",maxCapacity = 20}, 
    [86] = {model = "faction",maxCapacity = 20}, 
    [87] = {model = "nightshade",maxCapacity = 10}, 
    [88] = {model = "picador",maxCapacity = 30}, 
    [89] = {model = "sabregt",maxCapacity = 20}, 
    [90] = {model = "sabregt2",maxCapacity = 20}, 
    [91] = {model = "tampa",maxCapacity = 20}, 
    [92] = {model = "tornado3",maxCapacity = 20}, 
    [93] = {model = "tornado2",maxCapacity = 20}, 
    [94] = {model = "virgo", maxCapacity = 20}, 
    [95] = {model = "vigero",maxCapacity = 20}, 
	--################ SPORTS ##################
	[96] = {model = "ninef",maxCapacity = 10}, 
    [97] = {model = "ninef2",maxCapacity = 5}, 
    [98] = {model = "alpha",maxCapacity = 10}, 
    [99] = {model = "banshee", maxCapacity = 10}, 
    [100] = {model = "bestiagts", maxCapacity = 10}, 
    [101] = {model = "blista", maxCapacity = 5},  
    [102] = {model = "buffalo", maxCapacity = 50}, 
    [103] = {model = "buffalo2",maxCapacity = 50}, 
    [104] = {model = "carbonizzare", maxCapacity = 10}, 
    [105] = {model = "comet2",maxCapacity = 10}, 
    [106] = {model = "comet3",maxCapacity = 10}, 
    [107] = {model = "coquette",maxCapacity = 10}, 
    [108] = {model = "tampa2",maxCapacity = 10}, 
    [109] = {model = "feltzer2",maxCapacity = 10}, 
    [110] = {model = "furoregt",maxCapacity = 10}, 
    [111] = {model = "fusilade",maxCapacity = 10}, 
    [112] = {model = "jester", maxCapacity = 10}, 
    [113] = {model = "jester2",maxCapacity = 10}, 
    [114] = {model = "kuruma", maxCapacity = 40}, 
    [115] = {model = "lynx", maxCapacity = 10}, 
    [116] = {model = "massacro", maxCapacity = 10}, 
    [117] = {model = "massacro2",maxCapacity = 10}, 
    [118] = {model = "elegy2",maxCapacity = 10}, 
    [119] = {model = "elegy",maxCapacity = 10}, 
    [120] = {model = "khamelion", maxCapacity = 10}, 
    [121] = {model = "futo", maxCapacity = 10}, 
    [122] = {model = "omnis", maxCapacity = 10}, 
    [123] = {model = "penumbra", maxCapacity = 10}, 
    [124] = {model = "rapidgt", maxCapacity = 10}, 
    [125] = {model = "rapidgt2",maxCapacity = 10}, 
    [126] = {model = "schafter3",maxCapacity = 40}, 
    [127] = {model = "sultan", maxCapacity = 40}, 
    [128] = {model = "surano", maxCapacity = 10}, 
    [129] = {model = "seven70",maxCapacity = 10},  
    [130] = {model = "tropos",maxCapacity = 10}, 
    [131] = {model = "verlierer2",maxCapacity = 10}, 
    [132] = {model = "specter",maxCapacity = 10}, 
    [133] = {model = "specter2", maxCapacity = 10}, 
		--################ COUPES ##################
	[134] = {model = "ruiner", maxCapacity = 10}, 
    [135] = {model = "cogcabrio", maxCapacity = 10}, 
    [136] = {model = "exemplar", maxCapacity = 10}, 
    [137] = {model = "f620", maxCapacity = 10}, 
    [138] = {model = "felon", maxCapacity = 10}, 
    [139] = {model = "felon2",maxCapacity = 10}, 
    [140] = {model = "jackal", maxCapacity = 10}, 
    [141] = {model = "oracle", maxCapacity = 10}, 
    [142] = {model = "oracle2", maxCapacity = 10}, 
    [143] = {model = "sentinel",maxCapacity = 10}, 
    [144] = {model = "sentinel2", maxCapacity = 10}, 
    [145] = {model = "windsor",maxCapacity = 20}, 
    [146] = {model = "windsor2",maxCapacity = 30}, 
    [147] = {model = "zion",maxCapacity = 20}, 
    [148] = {model = "zion2",maxCapacity = 20}, 
	--################ SPORT CLASSICS ##################
	[149] = {model = "penetrator",maxCapacity = 10}, 
    [150] = {model = "casco",maxCapacity = 10}, 
    [151] = {model = "coquette2",maxCapacity = 10}, 
    [152] = {model = "pigalle",maxCapacity = 20},  
    [153] = {model = "stinger",maxCapacity = 10}, 
    [154] = {model = "stingergt",maxCapacity = 10}, 
    [155] = {model = "feltzer3",maxCapacity = 10}, 
    [156] = {model = "ztype",maxCapacity = 10}, 
    [157] = {model = "infernus2",maxCapacity = 10}, 
    [158] = {model = "manana",maxCapacity = 10}, 
    [159] = {model = "peyote",maxCapacity = 10}, 
    [160] = {model = "mamba",maxCapacity = 10}, 
    [161] = {model = "monroe",maxCapacity = 10}, 
    [162] = {model = "btype3",maxCapacity = 20}, 
	--################ SUPER ##################
	[163] = {model = "pfister811",maxCapacity = 5},
    [164] = {model = "ruston",maxCapacity = 5},
    [165] = {model = "adder",maxCapacity = 5},
    [166] = {model = "banshee2",maxCapacity = 5},
    [167] = {model = "bullet",maxCapacity = 5},
    [168] = {model = "cheetah",maxCapacity = 5},
    [169] = {model = "entityxf", maxCapacity = 5},
    [170] = {model = "sheava", maxCapacity = 5},
    [171] = {model = "fmj", maxCapacity = 5},
    [172] = {model = "infernus",maxCapacity = 5}, 
    [173] = {model = "osiris",maxCapacity = 5},
    [174] = {model = "le7b", maxCapacity = 5},
    [175] = {model = "nero",maxCapacity = 5},
    [176] = {model = "nero2", maxCapacity = 5},
    [177] = {model = "reaper", maxCapacity = 5},
    [178] = {model = "sultanrs", maxCapacity = 5},
    [179] = {model = "t20", maxCapacity = 5},
    [180] = {model = "turismor", maxCapacity = 5},
    [181] = {model = "tyrus", maxCapacity = 5},
    [182] = {model = "tempesta",maxCapacity = 5},
    [183] = {model = "vacca", maxCapacity = 5},
    [184] = {model = "voltic",maxCapacity = 5},
    [185] = {model = "prototipo", maxCapacity = 5},
    [186] = {model = "zentorno", maxCapacity = 5},
    [187] = {model = "italigtb",maxCapacity = 5},
    [188] = {model = "italigtb2",maxCapacity = 5},
    [189] = {model = "gp1", maxCapacity = 5},
    [190] = {model = "xa21",maxCapacity = 5},
    [191] = {model = "revolter", maxCapacity = 50},
	--################ SUPER ##################
	[192] = {model = "dinghy",  maxCapacity = 20},
    [193] = {model = "jetmax",  maxCapacity = 20},
    [194] = {model = "marquis",  maxCapacity = 50},
    [195] = {model = "seashark",  maxCapacity = 5},
    [196] = {model = "speeder",  maxCapacity = 50},
    [197] = {model = "squalo",  maxCapacity = 50},
    [198] = {model = "suntrap",  maxCapacity = 50},
    [199] = {model = "toro",  maxCapacity = 50},
    [200] = {model = "tropic",  maxCapacity = 50},
	--################ SUPER ##################
    [201] = {model = "buzzard2", maxCapacity = 50},
    [202] = {model = "frogger", maxCapacity = 50},
    [203] = {model = "maverick", maxCapacity = 50},
    [204] = {model = "supervolito2", maxCapacity = 50},
    [205] = {model = "swift", maxCapacity = 50},
    [206] = {model = "Swift2", maxCapacity = 50},
    [207] = {model = "volatus", maxCapacity = 50}
}

cargocontain = {
	[1] = {name="Lingot", id = 9, maxuserinv = 10},
    [2] = {name="Petrole", id = 43, maxuserinv = 70},
	[3] = {name="Planche", id = 20, maxuserinv = 40},
	[4] = {name="Biere", id = 25, maxuserinv = 70},
	[5] = {name="Pain", id = 5, maxuserinv = 99},
	[6] = {name="Filet de poisson", id = 22, maxuserinv = 99},
	[7] = {name="Bouteille", id = 27, maxuserinv = 50},
	[8] = {name="Metal", id = 2, maxuserinv = 99}
}
